import type { Config } from "tailwindcss";
import { colors } from "@apollo/space-kit/colors";

export default {
  content: [
    "./src/extension/devtools/panel.html",
    "./src/application/**/*.{html,ts,tsx}",
  ],
  theme: {
    fontFamily: {
      sans: ["Source Sans Pro", "sans-serif"],
      monospace: ["monospace"],
    },
    colors: {
      black: {
        DEFAULT: colors.black.base,
        darker: colors.black.darker,
        dark: colors.black.dark,
        base: colors.black.base,
        light: colors.black.light,
        lighter: colors.black.lighter,
      },
      blilet: {
        DEFAULT: colors.blilet.base,
        darkest: colors.blilet.darkest,
        darker: colors.blilet.darker,
        dark: colors.blilet.dark,
        base: colors.blilet.base,
        light: colors.blilet.light,
        lighter: colors.blilet.lighter,
        lightest: colors.blilet.lightest,
      },
      blue: {
        DEFAULT: colors.blue.base,
        darkest: colors.blue.darkest,
        darker: colors.blue.darker,
        dark: colors.blue.dark,
        base: colors.blue.base,
        light: colors.blue.light,
        lighter: colors.blue.lighter,
        lightest: colors.blue.lightest,
      },
      green: {
        DEFAULT: colors.green.base,
        darkest: colors.green.darkest,
        darker: colors.green.darker,
        dark: colors.green.dark,
        base: colors.green.base,
        light: colors.green.light,
        lighter: colors.green.lighter,
        lightest: colors.green.lightest,
      },
      grey: {
        DEFAULT: colors.grey.base,
        darker: colors.grey.darker,
        dark: colors.grey.dark,
        base: colors.grey.base,
        light: colors.grey.light,
        lighter: colors.grey.lighter,
      },
      indigo: {
        DEFAULT: colors.indigo.base,
        darkest: colors.indigo.darkest,
        darker: colors.indigo.darker,
        dark: colors.indigo.dark,
        base: colors.indigo.base,
        light: colors.indigo.light,
        lighter: colors.indigo.lighter,
        lightest: colors.indigo.lightest,
      },
      midnight: {
        DEFAULT: colors.midnight.base,
        darkest: colors.midnight.darkest,
        darker: colors.midnight.darker,
        dark: colors.midnight.dark,
        base: colors.midnight.base,
        light: colors.midnight.light,
        lighter: colors.midnight.lighter,
        lightest: colors.midnight.lightest,
      },
      orange: {
        DEFAULT: colors.orange.base,
        darkest: colors.orange.darkest,
        darker: colors.orange.darker,
        dark: colors.orange.dark,
        base: colors.orange.base,
        light: colors.orange.light,
        lighter: colors.orange.lighter,
        lightest: colors.orange.lightest,
      },
      pink: {
        DEFAULT: colors.pink.base,
        darkest: colors.pink.darkest,
        darker: colors.pink.darker,
        dark: colors.pink.dark,
        base: colors.pink.base,
        light: colors.pink.light,
        lighter: colors.pink.lighter,
        lightest: colors.pink.lightest,
      },
      purple: {
        DEFAULT: colors.purple.base,
        darkest: colors.purple.darkest,
        darker: colors.purple.darker,
        dark: colors.purple.dark,
        base: colors.purple.base,
        light: colors.purple.light,
        lighter: colors.purple.lighter,
        lightest: colors.purple.lightest,
      },
      red: {
        DEFAULT: colors.red.base,
        darkest: colors.red.darkest,
        darker: colors.red.darker,
        dark: colors.red.dark,
        base: colors.red.base,
        light: colors.red.light,
        lighter: colors.red.lighter,
        lightest: colors.red.lightest,
      },
      silver: {
        DEFAULT: colors.silver.base,
        darker: colors.silver.darker,
        dark: colors.silver.dark,
        base: colors.silver.base,
        light: colors.silver.light,
        lighter: colors.silver.lighter,
      },
      teal: {
        DEFAULT: colors.teal.base,
        darkest: colors.teal.darkest,
        darker: colors.teal.darker,
        dark: colors.teal.dark,
        base: colors.teal.base,
        light: colors.teal.light,
        lighter: colors.teal.lighter,
        lightest: colors.teal.lightest,
      },
      white: colors.white,
      yellow: {
        DEFAULT: colors.yellow.base,
        darkest: colors.yellow.darkest,
        darker: colors.yellow.darker,
        dark: colors.yellow.dark,
        base: colors.yellow.base,
        light: colors.yellow.light,
        lighter: colors.yellow.lighter,
        lightest: colors.yellow.lightest,
      },
    },
    extend: {},
  },
  plugins: [],
} satisfies Config;
