export const CLIENT_FOUND = "client-found";
export const REQUEST_TAB_ID = "request-tab-id";
export const DEVTOOLS_INITIALIZED = "devtools-initialized";
export const FIND_APOLLO_CLIENT = "find-apollo-client";
export const APOLLO_CLIENT_FOUND = "apollo-client-found";
export const CREATE_DEVTOOLS_PANEL = "create-devtools-panel";
export const ACTION_HOOK_FIRED = "action-hook-fired";
export const REQUEST_DATA = "request-data";
export const UPDATE = "update";
export const PANEL_OPEN = "panel-open";
export const PANEL_CLOSED = "panel-closed";
export const GRAPHIQL_REQUEST = "graphiql-request";
export const GRAPHIQL_RESPONSE = "graphiql-response";
export const RELOADING_TAB = "reloading-tab";
export const RELOAD_TAB_COMPLETE = "reload-tab-complete";
export const EMBEDDABLE_EXPLORER_URL =
  "https://explorer.embed.apollographql.com?showHeadersAndEnvVars=false";
